set up initial tests
UMassCDS/ada-collection pull request #9
Opened 2023-10-10 19:57 UTC by tnmygrwl

ignore auto-formatting changes in `setup_discount.py`

2023-10-11 21:37 UTC, ginic requested changes
The tests themselves look good and pass for me! 
I think there are some packaging nuances to take care of before this can be merged in. Besides moving the test dependencies from `requirements.txt` to `setup.py`, I think the unit tests should live under `ada_tools/tests`, instead of `ada_tools/src/tests` in order to keep the test code separate from application code. This avoids some potential issues with importing or packaging tests unnecessarily. You can see more details on that at https://pytest.org/en/7.4.x/explanation/goodpractices.html#tests-outside-application-code. I think you can just move the tests directory and everything will work as expected. 
Finally, you may want to add a note to the ada_tools README on how to run tests.

2023-10-11 21:37 UTC, ginic commented on ada_tools/requirements.txt
> +pytest-mock>=3.11.1
I think you should also list out the testing dependencies in the `ada_tools/setup.py` instead, just like the dev dependencies are listed separately. It's generally a good practice to call out test dependencies separately for packaging purposes and we should try to use the same conventions that the Red Cross is using.

2023-10-17 21:00 UTC, tnmygrwl commented
thanks for pointing it out @ginic, will update the PR with another small test along with it.

2023-10-17 21:17 UTC, tnmygrwl commented on ada_tools/requirements.txt
> +pytest-mock>=3.11.1
064a452c9acd1c5a012c06dc59755c740db29ed6

2023-10-17 21:41 UTC, tnmygrwl commented
@ginic this is ready for review. 

# Overview

Changes you've requested:
- e73e919bf571261f566fc6fd1755b2efa299bde0: removes the test from `/src/`
- 064a452c9acd1c5a012c06dc59755c740db29ed6: removes the dependency from `requirements.txt`
- 8402e569e06ab94aaa40ca765cce5a56a7620ec8: Adds another test, adds testing notes to the readme and modifies setup.py

Additional changes:
- 5492df8ce7e1435532d724dcb480284c5668f375: formatting across the package
- 29a0ef8b834f6edbe7012d70ecd7783a0780222c: resolving conflicts induced from #8 

lmk if there are test failures. I have commented the `test_main` out because testing Clicker CLI with fileops side effects is complicated and I'll get to it soon. ref: https://click.palletsprojects.com/en/8.1.x/testing/

2023-10-19 19:51 UTC, ginic approved these changes
Awesome! Looks great to me! Thanks for adding the tests.

2023-10-19 19:51 UTC, merged